version: 2.1

orbs:
  android: circleci/android@2.5.0
  ruby: circleci/ruby@2.1.4

jobs:
  lint:
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2023.11.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew lintDebug
      - android/save-gradle-cache

  unit_test:
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2023.11.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - store_test_results:
          path: ./app/build/test-results/testDebugUnitTest

  integration_test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2023.11.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests
      - store_test_results:
          path: ./app/build/outputs/androidTest-results/connected

  beta:
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2023.11.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - ruby/install-deps
      - run: bundle exec fastlane beta
      - android/save-gradle-cache

workflows:
  main:
    jobs:
      - lint
      - unit_test
      - integration_test
