version: 2.1

jobs:
  android-tests:
    docker:
      - image: cimg/android:2024.06.1
    working_directory: ~/project

    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      ANDROID_HOME: /opt/android/sdk

    steps:
      - checkout

      - run:
          name: Grant permission to gradlew
          command: chmod +x ./gradlew

      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      - run:
          name: Accept Licenses
          command: yes | sdkmanager --licenses

      - run:
          name: Install Emulator and System Image
          command: |
            sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

      - run:
          name: Create AVD
          command: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

      - run:
          name: Start Emulator
          command: |
            emulator -avd test -no-audio -no-window -no-boot-anim -gpu swiftshader_indirect &
            adb wait-for-device
            adb shell settings put global window_animation_scale 0 &
            adb shell settings put global transition_animation_scale 0 &
            adb shell settings put global animator_duration_scale 0

      - run:
          name: Run UI Tests
          command: ./gradlew connectedDebugAndroidTest

      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: unit-test-results

      - store_artifacts:
          path: app/build/outputs/androidTest-results/connected
          destination: ui-test-results

      - store_artifacts:
          path: app/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
          destination: screenshots

workflows:
  android_ci:
    jobs:
      - android-tests