name: Android CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ "master" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: app/build/reports/tests/testDebugUnitTest/

  build_apks:
    runs-on: ubuntu-latest
    outputs:
      build_artifact_path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app and test APKs
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - name: Upload APKs
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-apks
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/androidTest/debug/*.apk

  ui_tests:
    needs: [unit_tests, build_apks]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start Emulator
        uses: vgaidarji/android-github-actions-emulator@master
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 5
          emulator-options: "-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect"

      - name: Wait for Emulator to Boot
        run: |
          adb wait-for-device
          until adb shell getprop sys.boot_completed | grep -m 1 '1'; do sleep 1; done
          adb shell input keyevent 82

      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: app/build/outputs/androidTest-results/connected/

      - name: Dump Logcat
        if: always()
        run: adb logcat -d > logcat.txt

      - name: Upload Logcat
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: emulator-logcat
          path: logcat.txt