# .github/workflows/android-ci.yml
name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK and Create AVD
        run: |
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-33;default;x86_64" "platforms;android-33" "build-tools;33.0.0"
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

          echo "no" | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-33;default;x86_64" --device "pixel"

      - name: Start Emulator
        run: |
          ${ANDROID_HOME}/emulator/emulator -avd test_emulator -no-window -no-audio -gpu off &
          ${ANDROID_HOME}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          ${ANDROID_HOME}/platform-tools/adb devices -l
          ${ANDROID_HOME}/platform-tools/adb shell input keyevent 82

      - name: Run UI Tests on Emulator
        run: ./gradlew connectedDebugAndroidTest
