name: Android CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ "master" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: app/build/reports/tests/testDebugUnitTest/

  build_app:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android App Bundle
        run: ./gradlew bundleDebug

  ui_tests:
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run UI Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86
          disable-animations: true
          emulator-options: "-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -no-snapshot-save -no-accel"
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: app/build/outputs/androidTest-results/connected/

      - name: Upload Screenshots (if any)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: app/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected/**/*

      - name: Dump Logcat (for debugging if needed)
        if: always()
        run: adb logcat -d > logcat.txt

      - name: Upload Logcat
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: emulator-logcat
          path: logcat.txt