name: Android CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build Android App Bundle
        run: ./gradlew bundleDebug

      - name: Run Android Instrumented Tests and Capture Screenshots
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: app/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected/*/*

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            app/build/reports/tests/testDebugUnitTest/
            app/build/outputs/androidTest-results/connected/