# .github/workflows/android-ci.yml
name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK and Create AVD
        env:
          ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
        run: |
          mkdir -p ${ANDROID_AVD_HOME}

          # Install arm64-v8a system image instead of x86_64
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-33;default;arm64-v8a" "platforms;android-33" "build-tools;33.0.0" "platform-tools"
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

          # Create AVD with arm64-v8a system image
          echo "no" | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-33;default;arm64-v8a" --device "pixel" -f

          ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager list avd

      - name: Start Emulator
        env:
          ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
        run: |
          # The -gpu off flag is still useful for general stability in CI
          ${ANDROID_HOME}/emulator/emulator -avd test_emulator -no-window -no-audio -gpu off &
          ${ANDROID_HOME}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          ${ANDROID_HOME}/platform-tools/adb devices -l
          ${ANDROID_HOME}/platform-tools/adb shell input keyevent 82

      - name: Run UI Tests on Emulator
        run: ./gradlew connectedDebugAndroidTest
